/* cert-data.js — all certifications */
const ALL_CERTS = [
  { cat:'cat-ms',   issuer:'Dicoding Indonesia',        name:'Belajar Penerapan Data Science dengan Microsoft Fabric',                                          date:'Jan 2026 – Jan 2029',link:'#' },
  { cat:'cat-ds',   issuer:'Dicoding Indonesia',        name:'Belajar Dasar AI',                                                                                date:'Dec 2025 – Dec 2028',link:'#' },
  { cat:'cat-ds',   issuer:'Digital Talent Scholarship',name:'Kecerdasan Artifisial',                                                                           date:'Sep 2025',link:'#' },
  { cat:'cat-other',issuer:'Digital Talent Scholarship',name:'Keamanan Informasi',                                                                              date:'Sept 2025',link:'#' },
  { cat:'cat-other',issuer:'Digital Talent Scholarship',name:'Sosial Media Management untuk Brand Digital',                                                     date:'Sep 2025',link:'#' },
  { cat:'cat-ds',   issuer:'Digital Talent Scholarship',name:'Kecerdasan Artifisial',                                                                           date:'Sep 2025',link:'#' },
  { cat:'cat-other',issuer:'Digital Talent Scholarship',name:'Komunikasi',                                                                                      date:'Sep 2025',link:'#' },
  { cat:'cat-ds',   issuer:'Institut Teknologi Padang', name:'Symposium: Strengthening Research and Academic Collaboration between ITP and UTM',                date:'Aug 2025',link:'#' },
  { cat:'cat-other',issuer:'Brighten English',          name:'TOEFL',                                                                                           date:'Jul 2025 – Jul 2027',link:'#' },
  { cat:'cat-ms',   issuer:'Consultee & Company',       name:'Excel Mastery for Professionals: Effective Strategies for Data Analysis and Work Productivity',   date:'Apr 2025',link:'#' },
  { cat:'cat-ds',   issuer:'CertNexus',                 name:'Artificial Intelligence for Business Professional (AIBIZ)',                                       date:'Oct 2024',link:'#' },
  { cat:'cat-ds',   issuer:'CertNexus',                 name:'Data Science for Business Professional (DSBIZ)',                                                  date:'Jul 2024',link:'#' },
  { cat:'cat-ds',   issuer:'Kampus Merdeka',            name:'Magang & Studi Independen (MSIB) Data Science Batch 6',                                           date:'Jul 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Narasumber Webinar AI di Bidang Medis: Klasifikasi Kanker Payudara',                              date:'Jul 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Narasumber Webinar Exploratory Data Analysis with R: Teknik dan Praktik',                         date:'Jul 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Data Science: Pengenalan Principal Component Analysis (PCA) Untuk Riset',                         date:'Jun 2024',link:'#' },
  { cat:'cat-prog', issuer:'BISA AI Academy',           name:'Microservice dan MongoDB',                                                                        date:'Apr 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Word Embedding and NLP Research',                                                                 date:'May 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Computer Vision Case Study',                                                                      date:'Apr 2024',link:'#' },
  { cat:'cat-prog', issuer:'BISA AI Academy',           name:'Tutorial Game Development',                                                                       date:'Mar 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'LLM and Data Science for Maximizing Business in Industry',                                        date:'Mar 2024',link:'#' },
  { cat:'cat-other',issuer:'BISA AI Academy',           name:'Membuat Video Insight Menggunakan Tools AI',                                                      date:'Mar 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'Tips dan Strategi Menjadi Lulusan Terbaik dan Tepat Waktu',                                       date:'Jun 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'Menyusun Business Model Canvas Untuk Memulai Sebuah UMKM Bagi Mahasiswa',                         date:'May 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'Strategi Branding dan Digital Marketing Start-up',                                                date:'Apr 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Data-Driven Decision Making : Meningkatkan Kinerja dengan Data dan AI',                           date:'May 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'Transformasi Industri dengan AI : Kasus Sukses dari Berbagai Sektor',                             date:'May 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'How To Make Your Own Personal Branding',                                                          date:'May 2024',link:'#' },
  { cat:'cat-prog', issuer:'BISA AI Academy',           name:'Navigating the Future : Current Trends in UI/UX Design',                                          date:'Jun 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'AI Tools for Student Success : Enhancing Learning and Productivity',                              date:'Apr 2024',link:'#' },
  { cat:'cat-prog', issuer:'BISA AI Academy',           name:'Cloud Computing Untuk Hosting Website Sendiri',                                                   date:'Apr 2024',link:'#' },
  { cat:'cat-other',issuer:'BISA AI Academy',           name:'Cloud Computing Untuk Penyimpanan Data Seperti Google Drive',                                     date:'Mar 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Speech Classification Using Machine Learning',                                                    date:'May 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Spatial Data Analysis Using Machine Learning with R',                                             date:'May 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Introduction Data Mining',                                                                        date:'May 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Object Detection Deep Learning',                                                                  date:'May 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Machine Learning for Beginner',                                                                   date:'May 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Introduction to Image Recognition',                                                               date:'May 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Feature Extraction Speech',                                                                       date:'Apr 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Natural Language Processing (NLP) with Deep Learning',                                            date:'Apr 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Data Science with R',                                                                             date:'Apr 2024',link:'#' },
  { cat:'cat-other',issuer:'BISA AI Academy',           name:'SWOT Analysis in Business Planning for Beginners',                                                date:'Apr 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'Management',                                                                                      date:'Apr 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Image Processing',                                                                                date:'Apr 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Image Processing with OpenCV',                                                                    date:'Apr 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Deep Learning with Keras Python',                                                                 date:'Mar 2024',link:'#' },
  { cat:'cat-ds',   issuer:'BISA AI Academy',           name:'Machine Learning with Scikit-learn Python',                                                       date:'Mar 2024',link:'#' },
  { cat:'cat-prog', issuer:'BISA AI Academy',           name:'Python Fundamentals',                                                                             date:'Mar 2024',link:'#' },
  { cat:'cat-soft', issuer:'BISA AI Academy',           name:'Interpersonal Communication in Business',                                                         date:'Mar 2024',link:'#' },
  { cat:'cat-ms',   issuer:'BISA AI Academy',           name:'Basic Excel',                                                                                     date:'Feb 2024',link:'#' },
  { cat:'cat-soft', issuer:'Skill Academy by Ruangguru',name:'Kuasai Cara Berbicara Depan Umum dengan Teknik NLP',                                              date:'Nov 2021',link:'#' },
  { cat:'cat-ms',   issuer:'YEC Yureka Edukasi Cipta',  name:'Kelas Kilat: Microsoft Excel',                                                                    date:'Apr 2021',link:'#' },
  // { cat:'cat-ai',   issuer:'BISA AI Academy', name:'ITP',                date:'2024',link:'#' },
  /* ★ TAMBAH SERTIFIKAT LAIN DI SINI:
     { cat:'cat-ds|cat-ai|cat-soft|cat-prog|cat-ms|cat-other', issuer:'...', name:'...', date:'...', link:'https://...' }, */
];