/* projects.js — all 30 project definitions */
const PROJECTS = [
  /* ════ DATA SCIENCE & AI ════ */
  {
    num:'01', emoji:'🍃',
    tags:['ai','cv','fullstack','ds'],
    date:'Oct 2024 — Mar 2025',
    cats:['Computer Vision','AI / ML','Classification','Image Processing','Segmentation','Fullstack'],
    catColors:['syn-cyan','syn-purple','syn-orange'],
    title:'Tomato Plant Disease Classification System',
    descShort:'End-to-end AI web system for real-time tomato leaf disease detection from photos using CNN-based image classification.',
    features:['Real-time disease detection','SVM + Image Segmentation','Flask + React web app','Multi-class classification','94% accuracy'],
    problem:'Farmers lack fast, affordable tools to detect plant diseases early, leading to significant crop loss and economic damage.',
    solution:'Developed a AI models based image classification web system to identify tomato leaf diseases from uploaded photos in real-time using computer vision and machine learning.',
    contribution:[
      'Drove 97% reduction in time and cost compared to manual disease detection processes.',
      'Benchmarked 5 classification algorithms, achieved 94% accuracy on 4,100-image dataset via hyperparameter tuning.',
      'Built full pipeline: image acquisition → preprocessing → segmentation → feature extraction → SVM → Flask/React web app.',
      'Produced first-author scientific publication in SINTA 3 indexed journal (JPIT, DOI: 10.30591/jpit.v10i4.9404).',
      'Recognized as co-creator in registered software copyright (HKI / IP License, DJKI).'
    ],
    result:'94% accuracy · 97% time saved vs manual · SINTA 3 publication · IP Licensed',
    stack:['Python','OpenCV','Scikit-learn','Flask','SVM','HSV','GLCM','REST API'],
    tools:['Jupyter Notebook','VS Code','GitHub','Postman'],
    github:'https://github.com/puteriazli/TomatSehat-tomato-plant-disease-classification-system-with-AI/blob/main/README.md',
    demo:'https://youtu.be/QrW2xr9Nk54',
    portfolio:'',
    slides:['assets/projects/tomato plant disease/01.jpg','assets/projects/tomato plant disease/0.jpg','assets/projects/tomato plant disease/0.jpg','assets/projects/tomato plant disease/0.jpg','assets/projects/tomato plant disease/0.jpg']
  },
  {
    num:'02', emoji:'📡',
    tags:['ds','eda'],
    date:'May 2024',
    cats:['Data Analysis','Data Science','EDA','Data Visualization'],
    catColors:['syn-green','syn-blue'],
    title:'Analysis Data Air Quality Monitoring in Ancona City',
    descShort:'Comprehensive air quality data analysis for Ancona — temporal trends, pollutant correlations, and spatial visualization.',
    features:['Pollutant trend analysis','Spatial heatmaps','Correlation analysis','Multi-year dataset','Interactive Plotly charts'],
    problem:'Air quality data for Ancona city was scattered and unanalyzed, making it impossible to identify pollution patterns and high-risk periods.',
    solution:'Comprehensive Python analysis covering temporal trends, pollutant correlations, and spatial distribution across monitoring stations.',
    contribution:[
      'Analyzed multi-year dataset covering PM2.5, PM10, NO2, CO, and O3 metrics.',
      'Built temporal trend charts revealing seasonal pollution patterns and daily fluctuations.',
      'Performed correlation analysis between pollutants and weather variables.',
      'Created spatial heatmaps visualizing pollution distribution across monitoring stations.',
      'Derived insight report identifying high-risk periods and locations for public awareness.'
    ],
    result:'Comprehensive air quality report with temporal and spatial insights for Ancona',
    stack:['Python','Pandas','Matplotlib','Seaborn','Plotly','NumPy'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/5049',
    slides:['assets/projects/air quality ancona/.jpg']
  },
  {
    num:'03', emoji:'🏠',
    tags:['ai','ds','fullstack'],
    date:'Mar 2024 — May 2024',
    cats:['Data Science','Machine Learning','Regression','Fullstack','EDA','Data Preprocessing'],
    catColors:['syn-green','syn-blue','syn-orange'],
    title:'House Price Prediction System',
    descShort:'Regression ML model integrated into a fullstack web app for real-time property price estimation with feature importance visualization.',
    features:['Real-time price prediction','Feature importance viz','REST API integration','Interactive dashboard','Cross-validation tuning'],
    problem:'Buyers struggle to estimate fair market value without expert knowledge, often overpaying or missing good deals.',
    solution:'Regression ML model deployed as a fullstack web app with interactive dashboard showing predicted prices and model explainability.',
    contribution:[
      'Developed and deployed regression model for real-time house price prediction to production web app.',
      'Built interactive dashboard with feature importance visualization for interpretable predictions.',
      'Processed and cleaned real estate dataset with extensive feature engineering and EDA.',
      'Integrated model via Flask REST API consumed by React frontend with Tailwind CSS.',
      'Achieved competitive RMSE through cross-validation and ensemble model comparison.'
    ],
    result:'Interactive prediction dashboard · Feature importance viz · REST API deployment',
    stack:['Python','Scikit-learn','Flask','React','Tailwind CSS','Pandas','NumPy'],
    tools:['Jupyter Notebook','GitHub','Postman','VS Code'],
    github:'https://github.com/puteriazli/SmartProperty-automated-house-price-prediction-system/blob/main/readme.md',
    demo:'https://youtu.be/euN8VXaNDnA',
    portfolio:'',
    slides:['assets/projects/house price prediction/.png','assets/projects/house price prediction/.png','assets/projects/house price prediction/.png','assets/projects/house price prediction/.png','assets/projects/house price prediction/.png']
  },
    {
    num:'04', emoji:'👤',
    tags:['ai','cv','ds'],
    date:'[Fill Date]',
    cats:['Computer Vision','Deep Learning','AI / ML'],
    catColors:['syn-purple','syn-cyan'],
    title:'Face Recognition System for Security Application',
    descShort:'[DUMMY] Fill with your project description. Deep learning face recognition for identity verification.',
    features:['Real-time recognition','Identity verification','Deep learning model','OpenCV integration','[Feature 5]'],
    problem:'[DUMMY] Describe the problem this project solved.',
    solution:'[DUMMY] Describe your solution and technical approach.',
    contribution:[
      '[Bullet 1] What did you do?',
      '[Bullet 2]',
      '[Bullet 3]',
      '[Bullet 4]',
      '[Bullet 5]'],
    result:'[DUMMY] Replace with your real result metric',
    stack:['Python','PyTorch','DeepFace','TensorFlow'],
    tools:['Google Colab','Git & GitHub'],
    github:'https://github.com/puteriazli/Face-Recognition-for-Security-System',demo:'',portfolio:'',
    slides:['assets/projects/face recognition/.jpg','assets/projects/face recognition/.jpg','assets/projects/face recognition/.jpg','assets/projects/face recognition/.jpg','assets/projects/face recognition/.jpg']
  },
  {
    num:'05', emoji:'💬',
    tags:['nlp','ai','ds'],
    date:'Apr 2024 — May 2024',
    cats:['NLP','AI / ML','Transfer Learning'],
    catColors:['syn-pink','syn-cyan'],
    title:'Sentiment Analysis for DANA Aplication',
    descShort:'NLP pipeline using transfer learning to classify DANA fintech app reviews into nuanced sentiment categories beyond star ratings.',
    features:['Transfer learning NLP','Multi-class sentiment','10K+ reviews analyzed','HuggingFace Transformers','Temporal trend analysis'],
    problem:'Star ratings do not capture the nuanced user feelings about fintech apps — important feedback is lost in aggregated scores.',
    solution:'NLP pipeline using transfer learning (HuggingFace Transformers) to classify reviews into multi-class sentiment categories.',
    contribution:[
      'Scraped and preprocessed 10K+ user reviews from Google Play Store.',
      'Implemented transfer learning with HuggingFace Transformers, outperforming baseline models.',
      'Classified reviews into 4 sentiment classes (positive, negative, neutral, issue-specific).',
      'Performed deep EDA on sentiment distribution and keyword patterns per category.',
      'Visualized sentiment trends over time to identify product improvement windows.'
    ],
    result:'Transfer learning outperforms baseline · Multi-class sentiment across 10K+ reviews',
    stack:['Python','PyTorch','Transformers','HuggingFace','Pandas','Matplotlib','IndoBERT','XLM-RoBERTa'],
    tools:['Jupyter Notebook','Google Colab','GitHub'],
    github:'https://github.com/puteriazli/VoiceOfDANA-Sentiment-Intelligence-on-Digital-Payment-Reviews/blob/main/README.md',
    demo:'',portfolio:'',
    slides:['assets/projects/sentiment analysis dana/.png','assets/projects/sentiment analysis dana/.png','assets/projects/sentiment analysis dana/.png','assets/projects/sentiment analysis dana/.png',]
  },
    {
    num:'06', emoji:'🛣️',
    tags:['ai','cv','fullstack','ds'],
    date:'Jun 2024',
    cats:['Computer Vision','Deep Learning','AI / ML','Fullstack'],
    catColors:['syn-cyan','syn-purple','syn-orange'],
    title:'Road Damage Detection System',
    descShort:'CV model for automated road damage detection deployed as a web app. Capstone group project significantly reducing manual inspection effort.',
    features:['Automated damage detection','Severity classification','Flask web deployment','Crack & pothole detection','Group capstone project'],
    problem:'Manual road inspection is slow, costly, and inconsistent across large infrastructure networks.',
    solution:'Computer vision model deployed as a web app that automatically detects and classifies road surface damage from photos.',
    contribution:[
      'Led technical execution of group capstone from dataset collection to web deployment.',
      'Developed CV model to detect and classify road damage (cracks, potholes, deformation).',
      'Evaluated model performance across damage severity levels with custom metrics.',
      'Deployed model as Flask web app with React frontend for field inspection use.',
      'Reduced manual inspection time significantly through automated damage localization.'
    ],
    result:'Automated detection reducing manual inspection effort · Deployed web app',
    stack:['Python','TensorFlow','Flask','React','CNN','OpenCV','REST API'],
    tools:['Jupyter Notebook','GitHub','Postman'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4824',
    slides:['assets/projects/road damage detection/.png','assets/projects/road damage detection/.png','assets/projects/road damage detection/.png']
  },
  {
    num:'07', emoji:'📱',
    tags:['ds','timeseries','eda'],
    date:'May 2024 — Jun 2024',
    cats:['Data Science','Data Analysis','Time Series Analysis',' Data Visualization','EDA'],
    catColors:['syn-green','syn-yellow'],
    title:'WhatsApp Review — Time Series Analysis',
    descShort:'Comprehensive Python analysis of WhatsApp app reviews — daily/monthly trends, sentiment distribution, and negative review heatmaps.',
    features:['Time series visualization','Sentiment heatmaps','Keyword extraction','3-year trend analysis','Review frequency patterns'],
    problem:'App reviews contain temporal and behavioral patterns that go unanalyzed, missing critical signals about product quality over time.',
    solution:'Comprehensive Python analysis pipeline covering daily/monthly trends, sentiment distribution, and negative review timing heatmaps.',
    contribution:[
      'Analyzed 10K+ app store reviews across 3-year time window for pattern detection.',
      'Built daily, weekly, and monthly trend visualizations to track sentiment over time.',
      'Created review frequency heatmaps to identify peak complaint periods.',
      'Applied keyword extraction to identify the most common issues per time period.',
      'Derived actionable product insights from temporal review patterns.'
    ],
    result:'Multi-dimensional visual analysis of 10K+ reviews across 3-year window',
    stack:['Python','Pandas','Matplotlib','Seaborn','WordCloud'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'https://github.com/puteriazli/WhatsApp-Pulse-app-review-trend-sentiment-analysis/blob/main/README.md',
    demo:'',portfolio:'',
    slides:['assets/projects/whatsapp time series analysis/.jpg','assets/projects/whatsapp time series analysis/.jpg','assets/projects/whatsapp time series analysis/.jpg','assets/projects/whatsapp time series analysis/.jpg','assets/projects/whatsapp time series analysis/.jpg',]
  },
    {
    num:'8', emoji:'😷',
    tags:['ai','cv','ds'],
    date:'Jun 2024',
    cats:['Computer Vision','Deep Learning','AI/ML'],
    catColors:['syn-purple','syn-cyan'],
    title:'Face Mask Detection using Deep Learning',
    descShort:'Real-time deep learning model to detect mask usage, deployed as a web app with camera and image upload support.',
    features:['Real-time webcam detection','MobileNetV2 transfer learning','Flask web deployment','Image upload support','High inference speed'],
    problem:'Monitoring mask usage manually in public areas is inefficient and unscalable for large-scale compliance checking.',
    solution:'MobileNetV2-based transfer learning model for real-time mask detection deployed as a Flask web app supporting webcam and image upload.',
    contribution:[
      'Trained MobileNetV2-based transfer learning model on labeled mask/no-mask dataset.',
      'Integrated OpenCV for real-time webcam detection with bounding box annotation.',
      'Deployed model via Flask web app supporting both live camera and image upload.',
      'Achieved high accuracy through fine-tuning and data augmentation techniques.',
      'Optimized model inference speed for real-time performance on standard hardware.'
    ],
    result:'Real-time face mask detection via webcam & image upload with high accuracy',
    stack:['Python','TensorFlow','MobileNetV2','OpenCV'],
    tools:['Jupyter Notebook','GitHub','Postman'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4792',
    slides:['assets/projects/facemask detection/.jpg','assets/projects/facemask detection/.jpg','assets/projects/facemask detection/.jpg']
  },
  {
    num:'09', emoji:'🩺',
    tags:['ds','ai','medical','eda'],
    date:'Apr 2024',
    cats:['AI / ML','Data Science','Classification'],
    catColors:['syn-cyan','syn-green','syn-red'],
    title:'Breast Cancer Disease Classification',
    descShort:'ML model to classify breast tumors as malignant or benign based on clinical features with high diagnostic accuracy.',
    features:['Binary classification','5 algorithm comparison','Clinical feature analysis','Cross-validation','Explainable AI results'],
    problem:'Manual breast cancer diagnosis requires significant time and is prone to human error, especially in under-resourced settings.',
    solution:'ML classification model on the Wisconsin Breast Cancer dataset comparing 5 algorithms for malignant/benign tumor prediction.',
    contribution:[
      'Built binary classification model on Wisconsin dataset (569 samples, 30 features).',
      'Compared SVM, Random Forest, KNN, Logistic Regression, and Decision Tree classifiers.',
      'Performed extensive EDA including correlation matrix and feature distribution analysis.',
      'Optimized model with cross-validation achieving high precision and recall.',
      'Delivered explainable results with feature importance for clinical interpretation.'
    ],
    result:'High-accuracy binary diagnostic classifier with feature importance analysis',
    stack:['Python','Scikit-learn','Pandas','Matplotlib','Seaborn','SVM','Random Forest'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'https://github.com/puteriazli/CancerSense-AI-for-breast-cancer-classification/blob/main/breast%20cancer%20classification%20model.ipynb',
    demo:'',portfolio:'',
    slides:['assets/projects/breast cancer classification/.png','assets/projects/breast cancer classification/.png','assets/projects/breast cancer classification/.png',]
  },
  {
    num:'10', emoji:'🎙️',
    tags:['ds','speech','ai'],
    date:'May 2024',
    cats:['Data Science','AI/ML','Audio Extraction','Speech'],
    catColors:['syn-pink','syn-cyan'],
    title:'Comparison of Emotion Recognition Based on Voice Features',
    descShort:'Audio feature extraction pipeline (MFCC, Chroma, Mel Spectrogram) to compare and classify emotions from voice recordings.',
    features:['MFCC feature extraction','Chroma & Mel Spectrogram','6-emotion comparison','Spectral visualization','Audio signal processing'],
    problem:'Comparing emotion representations from audio signals requires precise feature extraction techniques that are not well-documented for beginners.',
    solution:'Pipeline extracting MFCC, Chroma, and Mel Spectrogram features from labeled emotion audio to compare and classify emotional content.',
    contribution:[
      'Extracted MFCC, Chroma, and Mel Spectrogram features from labeled emotion audio dataset.',
      'Compared feature representations across 6 emotion classes (anger, happiness, sadness, etc.).',
      'Visualized spectral feature distributions to identify distinguishing patterns per emotion.',
      'Evaluated classification accuracy using extracted features with multiple classifiers.',
      'Documented pipeline as reproducible notebook with detailed methodology.'
    ],
    result:'Feature-based emotion comparison pipeline with spectral visualization across 6 classes',
    stack:['Python','Librosa','MFCC','NumPy','Matplotlib','Scikit-learn'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/5106',
    slides:['assets/projects/Emotion Recognition/.png','assets/projects/Emotion Recognition/.png','assets/projects/Emotion Recognition/.png']
  },
  {
    num:'11', emoji:'📈',
    tags:['ds','eda'],
    date:'Mar 2024',
    cats:['Data Analysis','Data Science','EDA','Data Visualization'],
    catColors:['syn-green','syn-blue'],
    title:'Exploratory Data Analysis with R',
    descShort:'End-to-end EDA using R — descriptive statistics, ggplot2 visualizations, outlier detection, and correlation analysis.',
    features:['ggplot2 visualizations','Outlier detection','Correlation matrix','Descriptive statistics','R Markdown report'],
    problem:'Understanding distribution, patterns, and anomalies in complex datasets requires a systematic, reproducible exploration approach.',
    solution:'Full EDA workflow in R covering descriptive statistics, ggplot2 visualizations, outlier detection, and correlation analysis in an R Markdown report.',
    contribution:[
      'Performed full EDA workflow on structured dataset using R programming language.',
      'Created publication-quality visualizations with ggplot2 for distribution and correlation.',
      'Detected and handled outliers using IQR method and boxplot visualization.',
      'Computed descriptive statistics (mean, median, variance, skewness) per feature group.',
      'Delivered R Markdown report with interpretable findings and reproducible code.'
    ],
    result:'Full EDA report with statistical insights and reproducible R code',
    stack:['R','ggplot2','dplyr','tidyr','R Markdown','corrplot'],
    tools:['RStudio','GitHub'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4948',
    slides:['assets/projects/eda with r/.jpg']
  },
  {
    num:'12', emoji:'🔊',
    tags:['ai','ds','speech'],
    date:'May 2024',
    cats:['Speech','AI / ML','Data Science'],
    catColors:['syn-pink','syn-cyan','syn-green'],
    title:'AI Voice: Emotion Classification Based on Voice',
    descShort:'ML model to classify human emotions from voice recordings using MFCC features and deep learning.',
    features:['8-class emotion recognition','MFCC feature extraction','Deep neural network','Confusion matrix analysis','Audio preprocessing'],
    problem:'Human emotion in voice recordings is difficult to detect automatically without a purpose-built model and proper feature engineering.',
    solution:'ML model classifying emotions from voice recordings (angry, happy, sad, neutral, etc.) using MFCC features and deep learning.',
    contribution:[
      'Preprocessed and augmented audio dataset with 8 emotion classes.',
      'Extracted MFCC, ZCR, and RMS features from audio signals using Librosa.',
      'Trained deep neural network achieving strong F1-score across emotion categories.',
      'Visualized confusion matrix and per-class accuracy for model evaluation.',
      'Built complete pipeline from raw audio to classification result with feature visualization.'
    ],
    result:'Multi-class speech emotion classifier with feature visualization',
    stack:['Python','Librosa','TensorFlow','Scikit-learn','MFCC','NumPy'],
    tools:['Jupyter Notebook','Google Colab','GitHub'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4723',
    slides:['assets/projects/facemask detection/.jpg',]
  },


  /* ════ FULLSTACK ════ */
  {
    num:'13', emoji:'📰',
    tags:['fullstack','frontend','backend','database'],
    date:'Oct 2024 — Feb 2025',
    cats:['Fullstack','Authorization','Database'],
    catColors:['syn-orange','syn-blue','syn-green'],
    title:'University Article Publication Platform',
    descShort:'Full CMS with multi-role auth, review pipeline, and publication management for academic article submissions.',
    features:['Multi-role authentication','Review workflow','Article versioning','Admin dashboard','Publication management'],
    problem:'Manual academic submissions caused bottlenecks in review and publication workflows, delaying research dissemination.',
    solution:'Full CMS with user roles (admin, reviewer, author), review pipeline, and publication management for the university.',
    contribution:[
      'Built end-to-end academic publishing CMS with multi-role auth and access control.',
      'Implemented submission, peer review, editorial feedback, and publication workflow.',
      'Designed normalized MySQL schema for article metadata and versioning.',
      'Created rich text editor with category, keyword, and abstract management.',
      'Deployed system as production web app used by university department.'
    ],
    result:'End-to-end academic publishing CMS · Multi-role system in production',
    stack:['PHP','CodeIgniter 4','MySQL','JavaScript','HTML/CSS','Bootstrap'],
    tools:['VS Code','XAMPP','GitHub','phpMyAdmin'],
    github:'https://github.com/puteriazli/EduPublish-university-article-publication-web-platform-with-authorization',
    demo:'https://youtu.be/cy89fnQ5wfg',
    portfolio:'',
    slides:['assets/projects/website article/.png','assets/projects/website article/.png','assets/projects/website article/.png']
  },
  {
    num:'14', emoji:'🏫',
    tags:['frontend','other'],
    date:'[Fill Date]',
    cats:['Fullstack','Frontend'],
    catColors:['syn-orange','syn-yellow'],
    title:'SMK 13 Website Profile',
    descShort:'Official school profile website with programs, news, staff, and student information sections.',
    features:['Responsive design','Admin content panel','News publishing','Programs showcase','[Feature 5]'],
    problem:'[DUMMY] School lacked a professional digital presence to showcase programs and facilities.',
    solution:'Responsive school profile website with admin panel for content management and news publishing.',
    contribution:['[Bullet 1]','[Bullet 2]','[Bullet 3]','[Bullet 4]','[Bullet 5]'],
    result:'[DUMMY] Fully responsive school website delivered on schedule',
    stack:['HTML','CSS','JavaScript'],
    tools:['VS Code','GitHub','XAMPP'],
    github:'https://github.com/puteriazli/SMK-N-13-Sarolangun-profile-website',demo:'',portfolio:'',
    slides:[]
  },
  {
    num:'15', emoji:'🧑‍💻',
    tags:['frontend','other'],
    date:'May - Jun 2026',
    cats:['Frontend','Personal Project','UI/UX'],
    catColors:['syn-yellow','syn-green'],
    title:'Personal Portfolio Website',
    descShort:'This portfolio — built from scratch with 12+ themes, particle canvas, project filtering, and hover interactions.',
    features:['12+ color themes','Particle canvas BG','Project filter system','Smooth scroll reveals','Zero frameworks'],
    problem:'Needed a unique, high-performance portfolio that reflects my personality and technical skills without relying on templates.',
    solution:'Custom-built interactive website with zero JS frameworks, multi-theme CSS system, particle canvas, and animated project cards.',
    contribution:[
      'Designed and built entire portfolio from scratch with zero frameworks.',
      'Implemented 12+ color themes using CSS custom properties with runtime switching.',
      'Built interactive project filter with category/sub-category support for 30 projects.',
      'Added particle canvas background, scroll reveals, and micro-interactions.',
      'Optimized for performance: no heavy libs, CSS-only shapes, minimal paint operations.'
    ],
    result:'Zero-framework portfolio with 12+ themes, particles, and 30 projects',
    stack:['HTML','CSS','JavaScript','Canvas API','CSS Variables'],
    tools:['VS Code','GitHub Pages'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/portfolio web/.jpg','assets/projects/portfolio web/.jpg','assets/projects/portfolio web/.jpg']
  },

  /* ════ IOT ════ */
  {
    num:'18', emoji:'🌫️',
    tags:['iot'],
    date:'Oct 2024 — Nov 2024',
    cats:['IoT','Real-time System'],
    catColors:['syn-teal','syn-green'],
    title:'Air Quality Monitoring with Telegram Alert & LCD',
    descShort:'IoT pipeline using air quality sensors with automated Telegram bot alerts when pollution thresholds are exceeded.',
    features:['Real-time sensor reading','Telegram bot alerts','MQTT data pipeline','Live dashboard','Threshold-based alerting'],
    problem:'Air quality in urban areas often goes unmonitored in real-time, leaving residents unaware of dangerous pollution spikes.',
    solution:'IoT pipeline using ESP32 + air quality sensors with MQTT protocol and automated Telegram bot alerting when thresholds are exceeded.',
    contribution:[
      'Designed sensor circuit with ESP32/Arduino to continuously read air quality metrics.',
      'Implemented MQTT protocol for reliable sensor-to-server data transmission.',
      'Built Telegram Bot that fires real-time alerts when AQI exceeds safety thresholds.',
      'Created live monitoring dashboard displaying historical sensor readings and charts.',
      'Tested and calibrated sensor accuracy against reference measurements in the field.'
    ],
    result:'Real-time alerts delivered via Telegram within seconds of threshold breach',
    stack:['Arduino/ESP32','Python','MQTT','Telegram Bot API','C++','Dashboard'],
    tools:['Arduino IDE','VS Code','Telegram Developer Console'],
    github:'https://github.com/puteriazli/IoT-Air-Quality-Monitoring-with-Real-Time-Alert-via-Telegram/blob/main/README.md',
    demo:'',portfolio:'',
    slides:['assets/projects/iot air quality/.jpg','assets/projects/iot air quality/.jpg','assets/projects/iot air quality/.jpg']
  },
  // {
  //   num:'19', emoji:'💧',
  //   tags:['iot'],
  //   date:'[Fill Date]',
  //   cats:['IoT','Automation System'],
  //   catColors:['syn-teal'],
  //   title:'?',
  //   descShort:'[DUMMY] Sensor-based water quality monitoring system with dashboard.',
  //   features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
  //   problem:'[DUMMY]',
  //   solution:'[DUMMY]',
  //   contribution:[
  //     '[Bullet 1]',
  //     '[Bullet 2]',
  //     '[Bullet 3]',
  //     '[Bullet 4]',
  //     '[Bullet 5]'],
  //   result:'[DUMMY]',
  //   stack:['ESP32','Python','MQTT','MySQL'],
  //   tools:['Arduino IDE','VS Code'],
  //   github:'',demo:'',portfolio:'',
  //   slides:[]
  // },
  {
    num:'20', emoji:'🌡️',
    tags:['iot'],
    date:'[Oct 2023]',
    cats:['IoT','Distance Monitoring','Monitoring System','Real-time Monitoring'],
    catColors:['syn-teal'],
    title:'IoT-Based Distance Monitoring and Automatic LED Indicator System',
    descShort:'[DUMMY] Environmental monitoring with automated notifications.',
    features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
    problem:'An automated system is needed to detect object distance in real time and provide immediate visual feedback based on predefined distance ranges.',
    solution:'Developed a distance monitoring system using an ultrasonic sensor and NodeMCU ESP8266 that automatically activates different LEDs according to detected object distances.',
    contribution:[
      'Designed and assembled the electronic circuit using NodeMCU ESP8266, ultrasonic sensor, and LEDs.',
      'Developed firmware for real-time distance measurement using Arduino IDE.',
      'Implemented distance-based LED control logic for multiple threshold ranges.',
      'Configured sensor data acquisition and processing through NodeMCU.',
      'Conducted system testing and validation under different object distances.',
      'Prepared project documentation and demonstrated system functionality.'],
    result:'Successfully developed a real-time distance monitoring system with automatic LED indicators, achieving 100% functional accuracy during testing.',
    stack:['Arduino','Python','Sensor API','Alert System'],
    tools:['Arduino IDE','HC-SR04 Ultrasonic Sensor','NodeMCU ESP8266','LED'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot distance sensor/.jpg','assets/projects/iot distance sensor/.jpg','assets/projects/iot distance sensor/.jpg']
  },
  {
    num:'21', emoji:'🔌',
    tags:['iot'],
    date:'[Oct 2023]',
    cats:['IoT','Monitoring System','Automation System','Real-time Monitoring System'],
    catColors:['syn-teal'],
    title:'IoT-Based Light Intensity Monitoring and Automatic LED Control System',
    descShort:'Light Intensity Monitoring System',
    features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
    problem:'[DUMMY]',
    solution:'[DUMMY]',
    contribution:[
      '[Bullet 1]',
      '[Bullet 2]',
      '[Bullet 3]',
      '[Bullet 4]',
      '[Bullet 5]'],
    result:'[DUMMY]',
    stack:['ESP32','MQTT','Python','REST API'],
    tools:['Arduino IDE','LDR Sensor','LED','NodeMCU ESP8266'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot light sensor/.jpg','assets/projects/iot light sensor/.jpg','assets/projects/iot light sensor/.jpg',]
  },
  {
    num:'22', emoji:'📶',
    tags:['iot'],
    date:'Oct 2023',
    cats:['IoT','Monitoring System','Real-time Monitoring','Air Quality Sensor','Closed-Loop Control System'],
    catColors:['syn-teal','syn-green'],
    title:'IoT-Based Temperature Monitoring and Automatic LED Control System',
    descShort:'IoT Hardware for Air Quality Real-time Monitoring.',
    features:['Real-time temperature monitoring','Internet of Things (IoT)]','Hardware Developed','Data Monitoring','Automation System'],
    problem:'Manual environmental temperature monitoring is inefficient and lacks real-time feedback. An automated system is needed to continuously detect temperature changes and provide immediate visual indicators based on the detected conditions',
    solution:'Developed an IoT-based temperature monitoring system using DHT11 and NodeMCU ESP8266 to monitor temperature in real time and automatically control LEDs according to predefined temperature thresholds.',
    contribution:[
      'Designed and developed the electronic circuit for temperature sensing using NodeMCU ESP8266 and DHT11.',
      'Developed and programmed the temperature monitoring system using Arduino IDE.',
      'Implemented LED control logic based on predefined temperature thresholds.',
      'Conducted system testing and validation to ensure accurate responses to temperature changes.',
      'Prepared project documentation and demonstrated the system functionality infront stackholder.'],
    result:'Delivered a reliable closed-loop temperature monitoring system with accurate LED responses and 100% testing success.',
    stack:[ 'IoT','C/C++','Embedded Systems','Wi-Fi Communication','Closed-Loop Control System'],
    tools:['IDE Arduino','nodeMCU Esp8266','DHT11 Sensor','LED'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot air quality/.jpg','assets/projects/iot air quality/.jpg','assets/projects/iot air quality/.jpg',]
  },

  /* ════ DATABASE ════ */
  {
    num:'23', emoji:'🚗',
    tags:['database','other'],
    date:'[Fill Date]',
    cats:['Database'],
    catColors:['syn-blue'],
    title:'Database Management for Article Website',
    descShort:'Database system for managing damaged vehicle sales — inventory, transactions, and revenue reporting.',
    features:['Normalized schema','CRUD operations','Price history tracking','Sales reporting views','Sample data included'],
    problem:'Damaged vehicle sales data was managed in spreadsheets, causing errors and making analysis slow and error-prone.',
    solution:'Relational database system covering inventory, transactions, buyer/seller records, and SQL-based reporting.',
    contribution:[
      'Designed normalized relational database schema for vehicle and transaction management.',
      'Implemented CRUD for vehicle inventory with damage condition categorization.',
      'Built transaction recording system with buyer/seller data and price history.',
      'Created SQL queries and views for sales reporting and inventory summary.',
      'Delivered complete database with ER diagram, documentation, and sample data.'
    ],
    result:'Complete database management system for damaged vehicle sales operations',
    stack:['MySQL','SQL','PHP','HTML/CSS'],tools:['phpMyAdmin','XAMPP','VS Code'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/website article/.jpg','assets/projects/website article/.jpg']
  },
  // {
  //   num:'24', emoji:'🗄️',
  //   tags:['database','other'],
  //   date:'[Fill Date]',
  //   cats:['Database'],
  //   catColors:['syn-blue'],
  //   title:'Database Website Article Universitas',
  //   descShort:'Backend database design for the university article publication platform — schema, indexing, and query optimization.',
  //   features:['Full schema design','Query optimization','ER diagram','Foreign key constraints','Data dictionary'],
  //   problem:'The article publication platform needed a well-designed backend database to support fast search, filtering, and audit trails.',
  //   solution:'Complete relational database covering users, articles, reviews, categories, and publication history with optimized queries.',
  //   contribution:[
  //     'Designed complete relational database for the article publication system.',
  //     'Created tables for users, articles, reviews, categories, and publication history.',
  //     'Optimized queries for article search, filtering, and pagination performance.',
  //     'Implemented foreign key constraints and data integrity rules.',
  //     'Documented schema with ER diagram and data dictionary.'
  //   ],
  //   result:'Optimized database schema supporting full article publication workflow',
  //   stack:['MySQL','SQL','PHP','phpMyAdmin'],tools:['phpMyAdmin','XAMPP'],
  //   github:'',demo:'',portfolio:'',slides:[]
  // },
  // {
  //   num:'25', emoji:'📊',
  //   tags:['database','other'],
  //   date:'[Fill Date]',
  //   cats:['Database'],
  //   catColors:['syn-blue'],
  //   title:'Database Project — Dummy',
  //   descShort:'[DUMMY] Database design and management project.',
  //   features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
  //   problem:'[DUMMY]',solution:'[DUMMY]',
  //   contribution:['[Bullet 1]','[Bullet 2]','[Bullet 3]','[Bullet 4]','[Bullet 5]'],
  //   result:'[DUMMY]',stack:['MySQL','SQL','PHP'],tools:['phpMyAdmin','XAMPP'],
  //   github:'',demo:'',portfolio:'',slides:[]
  // },

  /* ════ SOFTWARE / APP ════ */
  {
    num:'26', emoji:'👕',
    tags:['app','other'],
    date:'[Fill Date]',
    cats:['Software','App'],
    catColors:['syn-green','syn-orange'],
    title:'Laundry Application System',
    descShort:'Full laundry management system — order tracking, customer management, pricing engine, and revenue reporting.',
    features:['Order lifecycle tracking','Customer history','Multi-service pricing','Revenue dashboard','Production-ready'],
    problem:'Laundry businesses relied on handwritten ledgers, causing order tracking errors and no visibility into revenue.',
    solution:'Full-featured laundry management system with order intake, status tracking, customer management, and income reporting.',
    contribution:[
      'Built full-featured laundry management system with order intake and status tracking.',
      'Implemented customer management with order history and service tracking.',
      'Created pricing engine supporting regular, express, and dry-clean service types.',
      'Built revenue dashboard with daily/monthly income reports and service analytics.',
      'Delivered production-ready application for small laundry business use.'
    ],
    result:'Production-ready laundry management system with full order lifecycle management',
    stack:['PHP','MySQL','JavaScript','HTML/CSS','Bootstrap'],tools:['VS Code','XAMPP','GitHub'],
    github:'',demo:'',portfolio:'',slides:[]
  },
  {
    num:'27', emoji:'⚡',
    tags:['app','other','backend'],
    date:'[Fill Date]',
    cats:['Software','App'],
    catColors:['syn-green','syn-yellow'],
    title:'Sistem Pembayaran Listrik',
    descShort:'Electricity billing and payment management system — meter reading, invoice generation, and payment tracking.',
    features:['Meter reading input','Auto bill calculation','Invoice generation','Payment confirmation','Outstanding bill reports'],
    problem:'Manual electricity billing created errors in consumption calculations and no easy way to track outstanding payments.',
    solution:'Electricity billing system with customer and meter management, automatic bill calculation, and payment confirmation workflow.',
    contribution:[
      'Built electricity payment management with customer and meter data management.',
      'Implemented meter reading input with automatic bill calculation per consumption tier.',
      'Created invoice generation and payment confirmation workflow.',
      'Built admin dashboard with outstanding bills, payment history, and collection reports.',
      'Delivered complete billing system simulation for utility management use case.'
    ],
    result:'Complete electricity billing system with automated invoice generation',
    stack:['PHP','MySQL','JavaScript','HTML/CSS'],tools:['VS Code','XAMPP','GitHub'],
    github:'',demo:'',portfolio:'',slides:[]
  },
  // {
  //   num:'28', emoji:'📱',
  //   tags:['app','other'],
  //   date:'[Fill Date]',
  //   cats:['Software','App'],
  //   catColors:['syn-green','syn-orange'],
  //   title:'Software Application — Dummy #1',
  //   descShort:'[DUMMY] Business process management application.',
  //   features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
  //   problem:'[DUMMY]',solution:'[DUMMY]',
  //   contribution:['[Bullet 1]','[Bullet 2]','[Bullet 3]','[Bullet 4]','[Bullet 5]'],
  //   result:'[DUMMY]',stack:['PHP','MySQL','JavaScript'],tools:['VS Code','XAMPP'],
  //   github:'',demo:'',portfolio:'',slides:[]
  // },
  // {
  //   num:'29', emoji:'🛠️',
  //   tags:['app','other'],
  //   date:'[Fill Date]',
  //   cats:['Software','App'],
  //   catColors:['syn-green','syn-purple'],
  //   title:'Software Application — Dummy #2',
  //   descShort:'[DUMMY] Management information system.',
  //   features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
  //   problem:'[DUMMY]',solution:'[DUMMY]',
  //   contribution:['[Bullet 1]','[Bullet 2]','[Bullet 3]','[Bullet 4]','[Bullet 5]'],
  //   result:'[DUMMY]',stack:['Python','Flask','MySQL','React'],tools:['VS Code','GitHub'],
  //   github:'',demo:'',portfolio:'',slides:[]
  // },
  // {
  //   num:'30', emoji:'💡',
  //   tags:['app','other'],
  //   date:'[Fill Date]',
  //   cats:['Software','App'],
  //   catColors:['syn-yellow','syn-orange'],
  //   title:'Software Application — Dummy #3',
  //   descShort:'[DUMMY] This is project slot #30 for you to fill.',
  //   features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
  //   problem:'[DUMMY]',solution:'[DUMMY]',
  //   contribution:['[Bullet 1]','[Bullet 2]','[Bullet 3]','[Bullet 4]','[Bullet 5]'],
  //   result:'[DUMMY]',stack:['PHP','MySQL','JavaScript'],tools:['VS Code','GitHub'],
  //   github:'',demo:'',portfolio:'',slides:[]
  // }
];

/* stack → color map */
const STACK_COLORS = {
  'Python':'syn-cyan','TensorFlow':'syn-blue','Scikit-learn':'syn-blue','Flask':'syn-orange',
  'React':'syn-yellow','Tailwind CSS':'syn-cyan','Pandas':'syn-green','NumPy':'syn-green',
  'OpenCV':'syn-purple','PyTorch':'syn-orange','Transformers':'syn-purple','HuggingFace':'syn-purple',
  'NLTK':'syn-pink','Librosa':'syn-pink','MFCC':'syn-purple','PHP':'syn-blue',
  'CodeIgniter 4':'syn-red','MySQL':'syn-green','JavaScript':'syn-yellow','HTML/CSS':'syn-yellow',
  'Bootstrap':'syn-blue','R':'syn-blue','ggplot2':'syn-orange','dplyr':'syn-green',
  'MobileNetV2':'syn-purple','CNN':'syn-blue','SVM':'syn-cyan','Random Forest':'syn-green',
  'Arduino/ESP32':'syn-teal','MQTT':'syn-teal','C++':'syn-blue','Plotly':'syn-orange',
  'Matplotlib':'syn-orange','Seaborn':'syn-yellow','WordCloud':'syn-pink','corrplot':'syn-purple',
  'DeepFace':'syn-purple','Node-RED':'syn-orange','Grafana':'syn-cyan','REST API':'syn-orange',
  'Canvas API':'syn-yellow','CSS Variables':'syn-purple','Telegram Bot API':'syn-teal',
  'tidyr':'syn-blue','R Markdown':'syn-orange','DeepLearning':'syn-purple',
};
function stackColor(t){return STACK_COLORS[t]||'syn-blue';}
