/* projects.js — all 30 project definitions */
const PROJECTS = [
  /* ════ DATA SCIENCE & AI ════ */
  {
    num:'01', emoji:'🍃',
    tags:['ai','cv','fullstack','ds','agriculture','image classification'],
    date:'Oct 2024 — Mar 2025',
    cats:['AI','Computer Vision','Digital Innovation','Smart Agriculture','Image Classification','Image Processing & Segmentation','Feature Extraction','Fullstack','Flask','REST API'],
    catColors:['syn-blue','syn-orange','syn-purple','syn-yellow','syn-pink','syn-cyan','syn-teal','syn-green','syn-red'],
    title:'Tomato Plant Disease Classification System Using AI Detection',
    features:['AI Automatic Disease Detection','Tomato leaf image upload','Real-time prediction','Classification & predictive dashboard','REST API','Responsive Web Interface'],
    problem:'Manual tomato disease identification is slow, inconsistent, and prone to human error. Farmers lack fast, affordable tools to detect plant diseases early, leading to significant crop loss and economic damage.',
    solution:'Developed a AI models based image classification web system to identify tomato leaf diseases from uploaded photos in real-time using computer vision and machine learning.',
    contribution:[
      'Drove 97% reduction in time and cost compared to manual disease detection processes.',
      'Collected and processed 4,100+ leaf images for ML dataset preparation.',
      'Built preprocessing, segmentation, GLCM, and HSV feature extraction pipeline.',
      'Benchmarked 5 classification algorithms to select the best-performing model.',
      'Trained and optimized SVM with Cross Validation and Hyperparameter Tuning, achieving 94% accuracy.',
      'Developed Flask REST API and integrated the AI model into a web application.',
      'Designed responsive frontend using HTML, CSS, and JavaScript.',
      'Conducted Black-box Testing for both model and web application.'
    ],
    result:'Achieved 94% classification accuracy and successfully deployed the AI model into a web-based detection system.',
    stack:['Python','OpenCV','Scikit-learn','Flask','REST API','JavaScript','SVM','HSV','GLCM'],
    tools:['Jupyter Notebook','VS Code','Python 3','Git & GitHub','Postman'],
    github:'https://github.com/puteriazli/TomatSehat-tomato-plant-disease-classification-system-with-AI/blob/main/README.md',
    demo:'https://youtu.be/QrW2xr9Nk54',
    portfolio:'',
    slides:['assets/projects/data science/tomato plant disease classification system using ai detection/',
      'assets/projects/data science/tomato plant disease classification system using ai detection/model training.png',
      'assets/projects/data science/tomato plant disease classification system using ai detection/model result.png',
      'assets/projects/data science/tomato plant disease classification system using ai detection/web interface.png']
  },
  {
    num:'02', emoji:'📡',
    tags:['ds','eda'],
    date:'May 2024',
    cats:['Data Science & Analysis','EDA','Dashboard','Data Visualization','Time Series Analysis','Forecasting','Geospatial Analysis','Data Sensor'],
    catColors:['syn-green','syn-blue','syn-yellow','syn-red','syn-orange','syn-pink','syn-teal','syn-blue','syn-purple'],
    title:'Dashboard & Forecasting Air Quality Monitoring in Ancona City',
    features:['Interactive dashboard','Air quality monitoring','Pollution forecasting','Time series analysis','Geospatial analysis','Anomaly detection','Interactive Plotly charts'],
    problem:'Large-scale air quality data made pollution trends and anomalies difficult to monitor effectively.',
    solution:'Built an analytical dashboard with forecasting to monitor air quality and predict pollution trends.',
    contribution:[
      'Processed 2.38M+ records from 2020-2023 across 19 features.',
      'Performed EDA and statistical analysis to discover pollution patterns.',
      'Developed time series forecasting models for pollutant prediction.',
      'Built an interactive Plotly dashboard for air quality monitoring.',
      'Applied geospatial analysis to compare environmental conditions.',
      'Detected sensor anomalies to improve data reliability.',
      'Built temporal trend charts revealing seasonal pollution patterns and daily fluctuations.',
      'Performed correlation analysis between pollutants and weather variables.',
      'Created spatial heatmaps visualizing pollution distribution across monitoring stations.',
      'Derived insight report identifying high-risk periods and locations for public awareness.'
    ],
    result:'Comprehensive air quality report with temporal and spatial insights for Ancona',
    stack:['Python','Pandas','Matplotlib','Seaborn','Plotly','NumPy'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/5049',
    slides:['assets/projects/data science/dashboard & forecasting air quality monitoring in europe city/',
      'assets/projects/data science/dashboard & forecasting air quality monitoring in europe city/',
      'assets/projects/data science/dashboard & forecasting air quality monitoring in europe city/',
      'assets/projects/data science/dashboard & forecasting air quality monitoring in europe city/',
      'assets/projects/data science/dashboard & forecasting air quality monitoring in europe city/'
    ]
  },
  {
    num:'03', emoji:'🏠',
    tags:['ai','ds','fullstack'],
    date:'Mar 2024 — May 2024',
    cats:['Machine Learning','Predictive Model','Regression','Fullstack','EDA','Data Preprocessing','Real Estate'],
    catColors:['syn-blue','syn-orange','syn-cyan','syn-teal','syn-yellow','syn-pink','syn-purple'],
    title:'House Price Prediction System Using Machine Learning',
    features:['House price prediction','Property input form','Feature importance','REST API','Prediction dashboard'],
    problem:'Buyers struggle to estimate fair market value without expert knowledge, often overpaying or missing good deals.',
    solution:'Regression ML model deployed as a fullstack web app with interactive dashboard showing predicted prices and model explainability.',
    contribution:[
      'Performed EDA and preprocessing on 2k housing datasets.',
      'Benchmarked 5 regression algorithms.',
      'Optimized Random Forest, achieving 19.32% MAPE and 77.14% R².',
      'Conducted feature engineering and feature importance analysis.',
      'Integrated model via Flask REST API consumed by React frontend with Tailwind CSS.',
      'Deployed regression model for real-time house price prediction to production web app.'
    ],
    result:'Delivered a house prediction system with 19.32% MAPE and 77.14% R².',
    stack:['Python','Scikit-learn','Flask','React','Tailwind CSS','Pandas','NumPy'],
    tools:['Jupyter Notebook','GitHub','Postman','VS Code'],
    github:'https://github.com/puteriazli/SmartProperty-automated-house-price-prediction-system/blob/main/readme.md',
    demo:'https://youtu.be/euN8VXaNDnA',
    portfolio:'',
    slides:['assets/projects/data science/house price prediction system using machine learning/',
      'assets/projects/data science/house price prediction system using machine learning/web interface.png',
      'assets/projects/data science/house price prediction system using machine learning/model training.png'
    ]
  },
    {
    num:'04', emoji:'👤',
    tags:['ai','cv','ds'],
    date:'[Jun 2026]',
    cats:['Computer Vision','Deep Learning','Face Recognition','PyTorch','Security System'],
    catColors:['syn-purple','syn-cyan','syn-pink','syn-blue','syn-teal'],
    title:'Face Recognition System for Security Application',
    features:['Face Recognition','Real-time recognition','Identity verification','Security System'],
    problem:'Digital Payment system need authentification mecanism with secure and fast. Traditional methods such a PIN and password can be guessed, stolen, and intercepted.',
    solution:'Developed a security system with face reognition for digital payments that cannot be faked with ordinary photos.',
    contribution:[
      'Developed Face Recognition model, achieved 99.58% accuracy during evaluation',
      'Training and Evaluating Model with 3.3M images across 9,131 identities using PyTorch',
      'Implemented MTCNN for face detection and InceptionResnetV1 pretrained on VGGFace2',
      'Optimized training using CrossEntropy + Label Smoothing',
    ],
    result:'Face recoginition models with 99,6% accuracy.',
    stack:['Python','PyTorch','DeepFace','Scikit-learn'],
    tools:['Google Colab','Git & GitHub'],
    github:'https://github.com/puteriazli/Face-Recognition-for-Security-System',demo:'',portfolio:'',
    slides:['assets/projects/data science/face recognition system for security application/',
      'assets/projects/data science/face recognition system for security application/',
      'assets/projects/data science/face recognition system for security application/'
    ]
  },
  {
    num:'05', emoji:'💬',
    tags:['nlp','ai','ds'],
    date:'Apr 2024 — May 2024',
    cats:['NLP','Sentiment Analysis','Hugging Face','IndoBERT','XLM-RoBERTa','Text Preprocessing'],
    catColors:['syn-green','syn-yellow','syn-orange','syn-pink','syn-purple','syn-red'],
    title:'Sentiment Analysis for DANA Aplication',
    features:['Sentiment prediction','Review analytics','Rating distribution','Time series analysis','Data Visualization'],
    problem:'Star ratings do not capture the nuanced user feelings about fintech apps — important feedback is lost in aggregated scores.',
    solution:'NLP pipeline using transfer learning (HuggingFace Transformers) to classify reviews into multi-class sentiment categories.',
    contribution:[
      'Scraped and preprocessed 740K+ app reviews from Google Play Store.',
      'Implemented and fine-tuned HuggingFace Transformers models, achived 69%, 68%, and 88% accuracy.',
      'Classified reviews into 3 sentiment classes (positive, negative, neutral).',
      'Evaluated models using Accuracy, Macro F1, and Cohens Kappa',
      'Performed and visualized text preprocessing and cleaning, EDA, time series, rating distribution, keyword pattern, and sentiment trends.'
    ],
    result:'3 sentiment analysis models with 69% and 68% accuary for 3 classes and 88% for binary classes',
    stack:['Python','PyTorch','Transformers','HuggingFace','Pandas','Matplotlib','IndoBERT','XLM-RoBERTa'],
    tools:['Jupyter Notebook','Google Colab','GitHub'],
    github:'https://github.com/puteriazli/VoiceOfDANA-Sentiment-Intelligence-on-Digital-Payment-Reviews/blob/main/README.md',
    demo:'',portfolio:'',
    slides:['assets/projects/data science/sentiment analysis for dana application/',
      'assets/projects/data science/sentiment analysis for dana application/',
      'assets/projects/data science/sentiment analysis for dana application/',
      'assets/projects/data science/sentiment analysis for dana application/'
    ]
  },
    {
    num:'06', emoji:'🛣️',
    tags:['ai','cv','fullstack','ds'],
    date:'Jun 2024',
    cats:['Computer Vision','Deep Learning','CNN','Fullstack','Flask','React'],
    catColors:['syn-cyan','syn-purple','syn-orange','syn-teal','syn-green','syn-yellow'],
    title:'Road Damage Detection System Using Deep Learning',
    features:['Road damage detection','Automated damage detection','Image upload','Automatic prediction','Dashboard','REST API'],
    problem:'Manual road inspection is slow, costly, and inconsistent across large infrastructure networks.',
    solution:'Computer vision model deployed as a web app that automatically detects and classifies road surface damage from photos.',
    contribution:[
      'Led a 6-member cross-functional team using Agile over 3 months.',
      'Managed project planning, task allocation, and weekly progress presentations.',
      'Designed AI architecture, UI/UX, React, Flask, and FastAPI integration.',
      'Developed a CNN model achieving 83% accuracy using real PUPR data.',
      'Reduced manual inspection activities by 90% through AI automation.'
    ],
    result:'Delivered an AI system with 83% accuracy while reducing manual inspection by 90%.',
    stack:['Python','TensorFlow','Flask','React','CNN','OpenCV','REST API'],
    tools:['Jupyter Notebook','GitHub','Postman'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4824',
    slides:['assets/projects/data science/road damage detection system using deep learning/',
      'assets/projects/data science/road damage detection system using deep learning/'
    ]
  },
  {
    num:'07', emoji:'📱',
    tags:['ds','timeseries','eda'],
    date:'May — Jun 2024',
    cats:['Data Analysis','Time Series Analysis','Trend & Sentiment Analysis','Product Analytics',' Data Visualization','EDA'],
    catColors:['syn-green','syn-yellow'],
    title:'Time Series Analysis for WhatsApp Review Application',
    features:['Time series analysis','Sentiment analysis','Rating distribution','User behavior insights','Trend analysis','App version analysis','Keyword extraction','Review frequency patterns'],
    problem:'App reviews contain temporal and behavioral patterns that go unanalyzed, missing critical signals about product quality over time.',
    solution:'Comprehensive Python analysis pipeline covering daily/monthly trends, sentiment distribution, and negative review timing heatmaps.',
    contribution:[
      'Analyzed 1.37M+ app reviews using EDA and data preprocessing.',
      'Identified top user-requested features, influential reviews, and sentiment patterns to derived actionable product insights',
      'Performed time series analysis on yearly, monthly, and hourly review trends.',
      'Evaluated application version performance based on positive, negative, and neutral reviews.',
      'Built interactive visualizations with Matplotlib to support data-driven product insights.',
      'Applied keyword extraction to identify the most common issues per time period.'
    ],
    result:'Delivered actionable insights on sentiment trends, app version quality, peak negative review periods, and user preferences from 1.37M+ reviews.',
    stack:['Python','Pandas','Matplotlib','Seaborn','WordCloud'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'https://github.com/puteriazli/WhatsApp-Pulse-app-review-trend-sentiment-analysis/blob/main/README.md',
    demo:'',portfolio:'',
    slides:['assets/projects/data science/time series analysis for whatsapp review application/',
      'assets/projects/data science/time series analysis for whatsapp review application/',
      'assets/projects/data science/time series analysis for whatsapp review application/',
      'assets/projects/data science/time series analysis for whatsapp review application/'
    ]
  },
    {
    num:'08', emoji:'😷',
    tags:['ai','cv','ds'],
    date:'Jun 2024',
    cats:['Computer Vision','Deep Learning','Image Preprocessing'],
    catColors:['syn-purple','syn-cyan'],
    title:'Face Mask Detection using Deep Learning',
    features:['Real-time webcam detection','MobileNetV2 transfer learning','Flask web deployment','Image upload support','High inference speed'],
    problem:'Monitoring mask usage manually in public areas is inefficient and unscalable for large-scale compliance checking.',
    solution:'MobileNetV2-based transfer learning model for real-time mask detection deployed as a Flask web app supporting webcam and image upload.',
    contribution:[
      'Trained MobileNetV2-based transfer learning model on labeled mask/no-mask dataset.',
      'Integrated OpenCV for real-time webcam detection with bounding box annotation.',
      'Deployed model via Flask web app supporting both live camera and image upload.',
      'Achieved high accuracy through fine-tuning and data augmentation techniques.',
      'Optimized model inference speed for real-time performance on standard hardware.'
    ],
    result:'Real-time face mask detection via webcam & image upload with high accuracy',
    stack:['Python','TensorFlow','MobileNetV2','OpenCV'],
    tools:['Jupyter Notebook','GitHub','Postman'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4792',
    slides:['assets/projects/data scienceface mask detection using deep learning/',
      'assets/projects/data scienceface mask detection using deep learning/',
      'assets/projects/data scienceface mask detection using deep learning/'
    ]
  },
  {
    num:'09', emoji:'🩺',
    tags:['ds','ai','medical','eda'],
    date:'Apr 2024',
    cats:['Data Science','Disease Classification','Predictive Models','AI For Healthcare','Data Preprocessing','EDA'],
    catColors:['syn-cyan','syn-green','syn-red'],
    title:'Breast Cancer Disease Classification',
    features:['Binary classification','5 algorithm comparison','Clinical feature analysis','Cross-validation','Explainable AI results'],
    problem:'Manual breast cancer diagnosis requires significant time and is prone to human error, especially in under-resourced settings.',
    solution:'ML classification model on the Wisconsin Breast Cancer dataset comparing 5 algorithms for malignant/benign tumor prediction.',
    contribution:[
      'Built binary classification model on Wisconsin dataset (569 samples, 30 features).',
      'Compared SVM, Random Forest, KNN, Logistic Regression, and Decision Tree classifiers.',
      'Performed extensive EDA including correlation matrix and feature distribution analysis.',
      'Optimized model with cross-validation achieving high precision and recall.',
      'Delivered explainable results with feature importance for clinical interpretation.'
    ],
    result:'High-accuracy binary diagnostic classifier with feature importance analysis',
    stack:['Python','Scikit-learn','Pandas','Matplotlib','Seaborn','SVM','Random Forest'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'https://github.com/puteriazli/CancerSense-AI-for-breast-cancer-classification/blob/main/breast%20cancer%20classification%20model.ipynb',
    demo:'',portfolio:'',
    slides:['assets/projects/data science/breast cancer disease classification/',
      'assets/projects/data science/breast cancer disease classification/',
      'assets/projects/data science/breast cancer disease classification/'
    ]
  },
  {
    num:'10', emoji:'🎙️',
    tags:['ds','speech','ai'],
    date:'May 2024',
    cats:['Data Science','Audio Extraction','Speech'],
    catColors:['syn-pink','syn-cyan'],
    title:'Comparison of Emotion Recognition Based on Voice Features',
    features:['MFCC feature extraction','Chroma & Mel Spectrogram','6-emotion comparison','Spectral visualization','Audio signal processing'],
    problem:'Comparing emotion representations from audio signals requires precise feature extraction techniques that are not well-documented for beginners.',
    solution:'Pipeline extracting MFCC, Chroma, and Mel Spectrogram features from labeled emotion audio to compare and classify emotional content.',
    contribution:[
      'Extracted MFCC, Chroma, and Mel Spectrogram features from labeled emotion audio dataset.',
      'Compared feature representations across 6 emotion classes (anger, happiness, sadness, etc.).',
      'Visualized spectral feature distributions to identify distinguishing patterns per emotion.',
      'Evaluated classification accuracy using extracted features with multiple classifiers.',
      'Documented pipeline as reproducible notebook with detailed methodology.'
    ],
    result:'Feature-based emotion comparison pipeline with spectral visualization across 6 classes',
    stack:['Python','Librosa','MFCC','NumPy','Matplotlib','Scikit-learn'],
    tools:['Jupyter Notebook','Google Colab'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/5106',
    slides:['assets/projects/data science/comparison of emotion recognition based on voice features/',
      'assets/projects/data science/comparison of emotion recognition based on voice features/',
      'assets/projects/data science/comparison of emotion recognition based on voice features/'
    ]
  },
  {
    num:'11', emoji:'📈',
    tags:['ds','eda'],
    date:'Mar 2024',
    cats:['Data Analysis','Data Science','EDA','Data Preprocessing','Data Visualization'],
    catColors:['syn-green','syn-blue'],
    title:'Exploratory Data Analysis with R',
    features:['ggplot2 visualizations','Outlier detection','Correlation matrix','Descriptive statistics','R Markdown report'],
    problem:'Understanding distribution, patterns, and anomalies in complex datasets requires a systematic, reproducible exploration approach.',
    solution:'Full EDA workflow in R covering descriptive statistics, ggplot2 visualizations, outlier detection, and correlation analysis in an R Markdown report.',
    contribution:[
      'Performed full EDA workflow on structured dataset using R programming language.',
      'Created publication-quality visualizations with ggplot2 for distribution and correlation.',
      'Detected and handled outliers using IQR method and boxplot visualization.',
      'Computed descriptive statistics (mean, median, variance, skewness) per feature group.',
      'Delivered R Markdown report with interpretable findings and reproducible code.'
    ],
    result:'Full EDA report with statistical insights and reproducible R code',
    stack:['R','ggplot2','dplyr','tidyr','R Markdown','corrplot'],
    tools:['RStudio','GitHub'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4948',
    slides:['assets/projects/data science/exploratory data analysis with r/',
      'assets/projects/data science/exploratory data analysis with r/'
    ]
  },
  {
    num:'12', emoji:'🔊',
    tags:['ai','ds','speech'],
    date:'May 2024',
    cats:['Speech','AI / ML','Data Science'],
    catColors:['syn-pink','syn-cyan','syn-green'],
    title:'AI Voice: Emotion Classification Based on Voice',
    features:['8-class emotion recognition','MFCC feature extraction','Deep neural network','Confusion matrix analysis','Audio preprocessing'],
    problem:'Human emotion in voice recordings is difficult to detect automatically without a purpose-built model and proper feature engineering.',
    solution:'ML model classifying emotions from voice recordings (angry, happy, sad, neutral, etc.) using MFCC features and deep learning.',
    contribution:[
      'Preprocessed and augmented audio dataset with 8 emotion classes.',
      'Extracted MFCC, ZCR, and RMS features from audio signals using Librosa.',
      'Trained deep neural network achieving strong F1-score across emotion categories.',
      'Visualized confusion matrix and per-class accuracy for model evaluation.',
      'Built complete pipeline from raw audio to classification result with feature visualization.'
    ],
    result:'Multi-class speech emotion classifier with feature visualization',
    stack:['Python','Librosa','TensorFlow','Scikit-learn','MFCC','NumPy'],
    tools:['Jupyter Notebook','Google Colab','GitHub'],
    github:'',demo:'',portfolio:'https://bisa.ai/portofolioku/detail/4723',
    slides:['assets/projects/data science/ai voice emotion classification based on voice/',
      'assets/projects/data science/ai voice emotion classification based on voice/',
      'assets/projects/data science/ai voice emotion classification based on voice/'
    ]
  },


  /* ════ FULLSTACK ════ */
  {
    num:'13', emoji:'📰',
    tags:['fullstack','frontend','backend','database'],
    date:'Oct 2024 — Des 2025',
    cats:['Fullstack','Authorization','Frontend','Backend','Respnsive Web','Database'],
    catColors:['syn-orange','syn-blue','syn-green','syn-pink','syn-purple','syn-red'],
    title:'University Article Publication Platform',
    features:['Multi-role authentication','Review workflow','Article versioning','Admin dashboard','Publication management'],
    problem:'Manual academic submissions caused bottlenecks in review and publication workflows, delaying research dissemination.',
    solution:'Full CMS with user roles (admin, reviewer, author), review pipeline, and publication management for the university.',
    contribution:[
      'Built end-to-end academic publishing CMS with multi-role auth and access control.',
      'Implemented submission, peer review, editorial feedback, and publication workflow.',
      'Designed normalized MySQL schema for article metadata and versioning.',
      'Created rich text editor with category, keyword, and abstract management.',
      'Deployed system as production web app used by university department.'
    ],
    result:'End-to-end academic publishing CMS · Multi-role system in production',
    stack:['PHP','CodeIgniter 4','MySQL','JavaScript','HTML/CSS','Bootstrap'],
    tools:['VS Code','XAMPP','GitHub','phpMyAdmin'],
    github:'https://github.com/puteriazli/EduPublish-university-article-publication-web-platform-with-authorization',
    demo:'https://youtu.be/cy89fnQ5wfg',
    portfolio:'',
    slides:['assets/projects/web/university article publication platform/',
      'assets/projects/web/university article publication platform/',
      'assets/projects/web/university article publication platform/'
    ]
  },
  {
    num:'14', emoji:'🏫',
    tags:['frontend','fullstack'],
    date:'Mei 2023 - Jun 2023',
    cats:['Frontend','Website Profile', 'School Website', 'Responsive Website'],
    catColors:['syn-yellow','syn-orange','syn-pink','syn-purple','syn-red'],
    title:'SMK Negeri 13 Sarolangun School Profile Website',
    features:['Responsive Design','Interactive Features with JavaScript','School Profile','School Advantages','Contact Information'],
    problem:'Technological advancements have made the internet the primary source of information. Without an official website, school information becomes less accessible and less effective to deliver.',
    solution:'Developed a school profile website that provides comprehensive information about the school, teachers, departments, facilities, vision & mission, accreditation, advantages, and contact details in a single, easily accessible platform.',
    contribution:[
      'Developed school web pages using HTML, CSS, and JavaScript.',
      'Built 9 core features, including Home, School Profile, Teachers, Departments, Facilities, Vision & Mission, Accreditation, School Advantages, and Contact',
      'Implemented a fully responsive design optimized for desktop, tablet, and mobile devices.',
      'Integrated 6 communication channels (Google Maps, Email, WhatsApp, Instagram, Facebook, and phone number).',
      'Developed the entire frontend, from layout design to interactive functionality using JavaScript.'],
    result:'The website successfully serves as an informative and responsive platform for school promotion, making it easier for students, parents, and the public to access official school information online.',
    stack:['HTML','CSS','JavaScript'],
    tools:['VS Code','Git','GitHub','Google Maps Embed'],
    github:'https://github.com/puteriazli/SMK-N-13-Sarolangun-profile-website',demo:'',portfolio:'',
    slides:['assets/projects/web/smk negeri 13 sarolangun school profile website/',
      'assets/projects/web/smk negeri 13 sarolangun school profile website/'
    ]
  },
  {
    num:'15', emoji:'🧑‍💻',
    tags:['frontend','fullstack'],
    date:'May - Jun 2026',
    cats:['Frontend','UI/UX','Web Interactive','Personal Website'],
    catColors:['syn-yellow','syn-green','syn-orange','syn-red'],
    title:'Personal Portfolio Website',
    features:['12+ color themes','Particle canvas BG','Project filter system','Smooth scroll reveals','Zero frameworks'],
    problem:'Needed a unique, high-performance portfolio that reflects my personality and technical skills without relying on templates.',
    solution:'Custom-built interactive website with zero JS frameworks, multi-theme CSS system, particle canvas, and animated project cards.',
    contribution:[
      'Designed and built entire portfolio from scratch with zero frameworks.',
      'Implemented 12+ color themes using CSS custom properties with runtime switching.',
      'Built interactive project filter with category/sub-category support for 30 projects.',
      'Added particle canvas background, scroll reveals, and micro-interactions.',
      'Optimized for performance: no heavy libs, CSS-only shapes, minimal paint operations.'
    ],
    result:'Zero-framework portfolio with 12+ themes, particles, and 30 projects',
    stack:['HTML','CSS','JavaScript','Canvas API','CSS Variables','UI/UX'],
    tools:['VS Code','GitHub Pages'],
    github:'',demo:'',portfolio:'https://puteriazli.github.io',
    slides:['assets/projects/web/personal portfolio website',
      'assets/projects/web/personal portfolio website'
    ]
  },

  /* ════ IOT ════ */
  {
    num:'16', emoji:'🌫️',
    tags:['iot'],
    date:'Oct 2024 — Nov 2024',
    cats:['IoT','Real-time Monitoring System','Telegram Sensor Notification','Smart System'],
    catColors:['syn-teal','syn-green','syn-orange','syn-pink'],
    title:'Air Quality Monitoring with Telegram Bot Notification & LCD',
    features:['Real-time sensor reading','Telegram bot alerts','MQTT data pipeline','Live dashboard','Threshold-based alerting'],
    problem:'Air quality in urban areas often goes unmonitored in real-time, leaving residents unaware of dangerous pollution spikes.',
    solution:'IoT pipeline using ESP32 + air quality sensors with MQTT protocol and automated Telegram bot alerting when thresholds are exceeded.',
    contribution:[
      'Designed sensor circuit with ESP32/Arduino to continuously read air quality metrics.',
      'Implemented MQTT protocol for reliable sensor-to-server data transmission.',
      'Built Telegram Bot that fires real-time alerts when AQI exceeds safety thresholds.',
      'Created live monitoring dashboard displaying historical sensor readings and charts.',
      'Tested and calibrated sensor accuracy against reference measurements in the field.'
    ],
    result:'Real-time alerts delivered via Telegram within seconds of threshold breach',
    stack:['Arduino/ESP32','Python','MQTT','Telegram Bot API','C++','Dashboard'],
    tools:['Arduino IDE','VS Code','Telegram Developer Console'],
    github:'https://github.com/puteriazli/IoT-Air-Quality-Monitoring-with-Real-Time-Alert-via-Telegram/blob/main/README.md',
    demo:'',portfolio:'',
    slides:['assets/projects/iot/air quality monitoring with telegram bot notification & lcd/',
      'assets/projects/iot/air quality monitoring with telegram bot notification & lcd/',
      'assets/projects/iot/air quality monitoring with telegram bot notification & lcd/'
    ]
  },
  {
    num:'17', emoji:'💧',
    tags:['iot'],
    date:'Des 2023',
    cats:['IoT','Automation System','Remote Control','Smart Home','LED Control','Blynk','Mobile App'],
    catColors:['syn-teal','syn-green','syn-yellow','syn-orange','syn-pink','syn-purple','syn-red'],
    title:'IoT LED Control System Using Blynk Application',
    features:['Real-time control of three LEDs using the Blynk mobile application.','Three Button widgets to independently control each LED.','Wireless communication over Wi-Fi.','Smartphone-based dashboard for device control.','Real-time response to user commands.','Simple and user-friendly interface.'],
    problem:'Manually controlling electronic devices requires users to be physically near the hardware. This limits flexibility and remote accessibility.',
    solution:'Develop an IoT system using NodeMCU ESP8266 integrated with the Blynk application, enabling users to remotely control LEDs through a smartphone over the internet.',
    contribution:[
      'Designed the NodeMCU ESP8266 circuit with three LEDs.',
      'Developed the LED control program using Blynk.',
      'Configured the Blynk dashboard with three Button widgets.',
      'Connected the system through Wi-Fi communication.',
      'Performed real-time LED control testing via smartphone.'],
    result:'The system successfully controlled three LEDs in real time through the Blynk mobile application with stable Wi-Fi communication.',
    stack:['Internet of Things (IoT)','Embedded Systems','C++','Wi-Fi Communication','Mobile IoT'],
    tools:['ESP8266','3 LEDs','Arduino IDE','Blynk IoT','Smartphone'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot/iot led control system using blynk application/',
      'assets/projects/iot/iot led control system using blynk application/',
      'assets/projects/iot/iot led control system using blynk application/'
    ]
  },
    {
    num:'18', emoji:'💧',
    tags:['iot'],
    date:'Des 2023',
    cats:['IoT','Automation System','Real-time Monitoring','Dashboard', 'Web Dashboard', 'Mobile Dashboard'],
    catColors:['syn-cyan','syn-blue','syn-teal','syn-green','syn-yellow','syn-orange'],
    title:'Temperature and Humidity Monitoring System Using Blynk',
    features:['Real-time temperature and humidity monitoring with a DHT sensor','Display sensor data on the Blynk Web & Mobile Dashboard','Visualize sensor readings using Gauge Widgets','Display historical data using Chart Widgets','Wireless data transmission via Wi-Fi'],
    problem:'Manual monitoring of temperature and humidity is inefficient and difficult to perform remotely. Sensor data is also harder to interpret without a visual dashboard.',
    solution:'Develop an IoT monitoring system using NodeMCU ESP8266 and Blynk to display real-time temperature and humidity data on both web and mobile dashboards.',
    contribution:[
      'Designed the NodeMCU, three LEDs, and DHT sensor circuit',
      'Integrated the hardware with the Blynk platform.',
      'Built Web and Mobile Dashboards.',
      'Displayed sensor data using Gauge and Chart widgets.',
      'Conducted real-time monitoring tests.'],
    result:'The system successfully displayed real-time temperature and humidity data on both the Blynk Web Dashboard and Mobile Dashboard using Gauge and Chart widgets.',
    stack:['Internet of Things (IoT)','Embedded Systems','C++','Wi-Fi Communication', 'Cloud IoT'],
    tools:['NodeMCU ESP8266','DHT11 Sensor','3 LEDs', 'Arduino IDE','Blynk','Smartphone'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot/temperature and humidity monitoring system using blynk/',
      'assets/projects/iot/temperature and humidity monitoring system using blynk/',
      'assets/projects/iot/temperature and humidity monitoring system using blynk/'
    ]
  },
  {
    num:'19', emoji:'💧',
    tags:['iot'],
    date:'Des 2023',
    cats:['IoT','Automation System','Real-time Monitoring','IoT Dashboard','Thinger.io','LED Control'],
    catColors:['syn-green','syn-yellow','syn-orange','syn-pink','syn-purple','syn-red'],
    title:'LED Control and Temperature-Humidity Monitoring System Using Thinger.io',
    features:['Real-time control of three LEDs using dashboard buttons','Real-time temperature and humidity monitoring with a DHT sensor','Display temperature and humidity data on the Thinger.io dashboard.','Wireless communication via Wi-Fi.','Web-based IoT dashboard for monitoring and control.'],
    problem:'Manual device control and environmental monitoring are inefficient and cannot be performed remotely. The collected data is also difficult to monitor without a centralized dashboard.',
    solution:'Develop an IoT system using NodeMCU ESP8266 that enables remote LED control through Thinger.io while displaying real-time temperature and humidity data.',
    contribution:[
      'Designed the NodeMCU, three LEDs, and DHT sensor circuit',
      'Developed the LED control program integrated with Thinger.io.',
      'Implemented DHT sensor data acquisition and cloud integration.',
      'Built a dashboard using Button and Data Display widgets.',
      'Conducted real-time testing for monitoring and device control.'],
    result:'The system successfully controlled three LEDs through the Thinger.io dashboard while displaying real-time temperature and humidity data over a stable Wi-Fi connection.',
    stack:['Internet of Things (IoT)','Embedded Systems','C++','Wi-Fi Communication', 'Cloud IoT'],
    tools:['NodeMCU ESP8266','DHT11 Sensor', 'DHT22 Sensor','3 LEDs', 'Arduino IDE','Thinger.io'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot/led control and temperature-humidity monitoring system using thinger.io/',
      'assets/projects/iot/led control and temperature-humidity monitoring system using thinger.io/',
      'assets/projects/iot/led control and temperature-humidity monitoring system using thinger.io/'
    ]
  },
  {
    num:'20', emoji:'💧',
    tags:['iot'],
    date:'Nov 2023',
    cats:['IoT', 'Temperature & Humidity Monitoring','Real-time Monitoring', 'Blynk', 'Embedded Systems'],
    catColors:['syn-red','syn-green','syn-pink','syn-orange','syn-yellow'],
    title:'Temperature and Humidity Monitoring System Based on IoT',
    features:['Real-time temperature monitoring','Real-time humidity monitoring.','Display sensor values using a Text widget.','Visualize sensor data with a Time Series Chart.','Wireless data transmission via Wi-Fi.','Monitor environmental changes over a selected time period.'],
    problem:'Manual monitoring of temperature and humidity is inefficient and does not provide real-time insights. Data analysis is also difficult without visualization.',
    solution:'Develop an IoT system using a NodeMCU ESP8266 and DHT sensor to collect, transmit, and display sensor data in real time through a dashboard.',
    contribution:[
      'Designed the NodeMCU ESP8266 and DHT sensor circuit.',
      'Developed the sensor data acquisition program.',
      'Integrated sensor data with the IoT dashboard.',
      'Displayed readings using Text widgets and Time Series Charts.',
      'Conducted a 10-minute real-time monitoring test.'],
    result:'The system successfully displayed real-time temperature and humidity values through Text widgets and visualized data trends using a Time Series Chart during the testing period.',
    stack:['Internet of Things (IoT)','Embedded Systems','C++','Wi-Fi Communication'],
    tools:['ESP8266', 'NodeMCU', 'DHT11 Sensor', 'DHT22 Sensor', 'Arduino IDE', 'Blynk IoT Platform'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot/temperature and humidity monitoring system based on iot/',
      'assets/projects/iot/temperature and humidity monitoring system based on iot/',
      'assets/projects/iot/temperature and humidity monitoring system based on iot/'
    ]
  },
  {
    num:'21', emoji:'🌡️',
    tags:['iot'],
    date:'Oct 2023',
    cats:['IoT','Distance Monitoring','Monitoring System','Real-time Monitoring'],
    catColors:['syn-green','syn-yellow','syn-orange','syn-pink'],
    title:'Distance Monitoring and Automatic LED Indicator System',
    features:['[Feature 1]','[Feature 2]','[Feature 3]','[Feature 4]','[Feature 5]'],
    problem:'An automated system is needed to detect object distance in real time and provide immediate visual feedback based on predefined distance ranges.',
    solution:'Developed a distance monitoring system using an ultrasonic sensor and NodeMCU ESP8266 that automatically activates different LEDs according to detected object distances.',
    contribution:[
      'Designed and assembled the electronic circuit using NodeMCU ESP8266, ultrasonic sensor, and LEDs.',
      'Developed firmware for real-time distance measurement using Arduino IDE.',
      'Implemented distance-based LED control logic for multiple threshold ranges.',
      'Configured sensor data acquisition and processing through NodeMCU.',
      'Conducted system testing and validation under different object distances.',
      'Prepared project documentation and demonstrated system functionality.'],
    result:'Successfully developed a real-time distance monitoring system with automatic LED indicators, achieving 100% functional accuracy during testing.',
    stack:['Arduino','Python','Sensor API','Alert System'],
    tools:['Arduino IDE','HC-SR04 Ultrasonic Sensor','NodeMCU ESP8266','LED'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot/distance monitoring and automatic led indicator system/',
      'assets/projects/iot/distance monitoring and automatic led indicator system/',
      'assets/projects/iot/distance monitoring and automatic led indicator system/'
    ]
  },
  {
    num:'22', emoji:'🔌',
    tags:['iot'],
    date:'Oct 2023',
    cats:['IoT','Smart Monitoring System','Automation System','Real-time Monitoring System'],
    catColors:['syn-green','syn-orange','syn-purple','syn-red'],
    title:'Light Intensity Monitoring with Automatic LED Control System',
    features:[
      'Real-time light intensity monitoring via serial output',
      'Dual LED indicators based on light thresholds',
      'Automatic response to environmental lighting changes',
      'Simple smart lighting simulation system'],
    problem:'Manual lighting systems often waste electrical energy because lights remain on even when sufficient natural light is available.',
    solution:'Develop an LDR-based light intensity detection system using the NodeMCU ESP8266 to automatically control LEDs based on predefined thresholds as a prototype of an intelligent lighting system.',
    contribution:[
      'Implemented a stable threshold-based decision system across two key ranges (200–400 and 500–600) with less than 10% reading error under dynamic lighting conditions.',
      'Achieved ~95% consistency in environmental light classification (dark–dim–bright) across repeated tests using ADC range 0–1024.',
      'Eliminated manual intervention in simulated lighting control through threshold-based decision automation.'],
    result:'The system successfully differentiates dark, dim, and bright conditions and activates LEDs consistently based on LDR value ranges.',
    stack:['Internet of Things (IoT)','Embedded Systems','C++','Wi-Fi Communication'],
    tools:['Arduino IDE','LDR Sensor','LED','NodeMCU ESP8266'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot/light intensity monitoring with automatic led control system/',
      'assets/projects/iot/light intensity monitoring with automatic led control system/',
      'assets/projects/iot/light intensity monitoring with automatic led control system/'
    ]
  },
  {
    num:'23', emoji:'📶',
    tags:['iot'],
    date:'Oct 2023',
    cats:['IoT','Monitoring System','Real-time Monitoring','Air Quality Sensor','Closed-Loop Control System'],
    catColors:['syn-teal','syn-purple','syn-green','syn-orange','syn-yellow','syn-pink'],
    title:'Temperature Monitoring and Automatic LED Control System',
    features:['Real-time temperature monitoring','Internet of Things (IoT)]','Hardware Developed','Data Monitoring','Automation System'],
    problem:'Manual environmental temperature monitoring is inefficient and lacks real-time feedback. An automated system is needed to continuously detect temperature changes and provide immediate visual indicators based on the detected conditions',
    solution:'Developed an IoT-based temperature monitoring system using DHT11 and NodeMCU ESP8266 to monitor temperature in real time and automatically control LEDs according to predefined temperature thresholds.',
    contribution:[
      'Designed and developed the electronic circuit for temperature sensing using NodeMCU ESP8266 and DHT11.',
      'Developed and programmed the temperature monitoring system using Arduino IDE.',
      'Implemented LED control logic based on predefined temperature thresholds.',
      'Conducted system testing and validation to ensure accurate responses to temperature changes.',
      'Prepared project documentation and demonstrated the system functionality infront stackholder.'],
    result:'Delivered a reliable closed-loop temperature monitoring system with accurate LED responses and 100% testing success.',
    stack:[ 'IoT','C/C++','Embedded Systems','Wi-Fi Communication','Closed-Loop Control System'],
    tools:['IDE Arduino','nodeMCU Esp8266','DHT11 Sensor','LED'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/iot/temperature monitoring and automatic led control system/',
      'assets/projects/iot/temperature monitoring and automatic led control system/',
      'assets/projects/iot/temperature monitoring and automatic led control system/'
    ]
  },

  /* ════ DATABASE ════ */
  {
    num:'24', emoji:'🚗',
    tags:['database','other'],
    date:'[Fill Date]',
    cats:['Database'],
    catColors:['syn-blue'],
    title:'Database Management for Article Website',
    features:['Normalized schema','CRUD operations','Price history tracking','Sales reporting views','Sample data included'],
    problem:'Damaged vehicle sales data was managed in spreadsheets, causing errors and making analysis slow and error-prone.',
    solution:'Relational database system covering inventory, transactions, buyer/seller records, and SQL-based reporting.',
    contribution:[
      'Designed normalized relational database schema for vehicle and transaction management.',
      'Implemented CRUD for vehicle inventory with damage condition categorization.',
      'Built transaction recording system with buyer/seller data and price history.',
      'Created SQL queries and views for sales reporting and inventory summary.',
      'Delivered complete database with ER diagram, documentation, and sample data.'
    ],
    result:'Complete database management system for damaged vehicle sales operations',
    stack:['MySQL','SQL','PHP','HTML/CSS'],tools:['phpMyAdmin','XAMPP','VS Code'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/database/database management for article website/',
      'assets/projects/database/database management for article website/'
    ]
  },

  /* ════ SOFTWARE / APP ════ */
    {
    num:'25', emoji:'⚡',
    tags:['app','other','backend'],
    date:'Jul 2023',
    cats:['Software','Desktop Application','Billing System','Utility Management','Java','NetBeans'],
    catColors:['syn-blue','syn-teal','syn-green','syn-yellow','syn-orange','syn-pink'],
    title:'Electricity Payment Calculation and Billing System',
    features:['Meter reading input','Auto bill calculation','Invoice generation','Payment confirmation','Outstanding bill reports'],
    problem:'Manual electricity billing created errors in consumption calculations and no easy way to track outstanding payments.',
    solution:'Developed a desktop application that automatically calculates electricity bills and payment confirmation workflow.',
    contribution:[
      'Built electricity payment management with customer and meter data management.',
      'Implemented meter reading input with automatic bill calculation per consumption tier.',
      'Created invoice generation and payment confirmation workflow.',
      'Built admin dashboard with outstanding bills, payment history, and collection reports.',
      'Delivered complete billing system simulation for utility management use case.'
    ],
    result:'Transformation and improve billing system with automated invoice generation',
    stack:['Java','Java Swing','MySQL','JDBC','OOP'],
    tools:['NetBeans IDE'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/software/electricity payment calculation and billing system/',
      'assets/projects/software/electricity payment calculation and billing system/'
    ]
  },
  {
    num:'26', emoji:'👕',
    tags:['app','other'],
    date:'Jul 2023',
    cats:['Software','App','Desktop Application','Laundry Management'],
    catColors:['syn-green','syn-teal','syn-yellow','syn-orange','syn-blue'],
    title:'Laundry Billing and Order Management System',
    features:['Customer management','Laundry order management','Automatic price calculation','Order status tracking','Transaction history','Service CRUD management'],
    problem:'Laundry businesses relied on handwritten ledgers, causing order tracking errors and no visibility into revenue.',
    solution:'Full-featured laundry management system with order intake, status tracking, customer management, and income reporting.',
    contribution:[
      'Built full-featured laundry management system with order intake and status tracking.',
      'Implemented customer management with order history and service tracking.',
      'Created pricing engine supporting regular, express, and dry-clean service types.',
      'Built revenue dashboard with daily/monthly income reports and service analytics.',
      'Delivered production-ready application for small laundry business use.'
    ],
    result:'Production-ready laundry management system with full order lifecycle management',
    stack:['Java','Java Swing','MySQL','JDBC','OOP'],
    tools:['Java','NetBeans IDE'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/software/laundry billing and order management system/',
      'assets/projects/software/laundry billing and order management system/'
    ]
  },
  {
    num:'27', emoji:'⚡',
    tags:['app','other','software'],
    date:'Mar 2023',
    cats:['Software','App','Desktop Application','Academic Management','Student Information System'],
    catColors:['syn-green','syn-yellow','syn-orange','syn-pink','syn-purple'],
    title:'Graduation and Academic Honors Calculation System Using Java NetBeans',
    features:['Student management','Course grade input','Final grade calculation','Graduation eligibility evaluation','Academic honors classification','Academic report generation','Student CRUD operations'],
    problem:'Graduation and academic honors are calculated manually, making the process inefficient, time-consuming, and error-prone.',
    solution:'Developed a desktop application that automates graduation eligibility and academic honors calculations.',
    contribution:[
      'Designed the application interface.',
      'Implemented academic calculation logic.',
      'Developed student CRUD features.',
      'Integrated the database.',
    ],
    result:'Improved consistency and accuracy of academic evaluations.',
    stack:['Java','Java Swing','MySQL','JDBC','OOP'],
    tools:['Java','NetBeans IDE'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/software/graduation and academic honors calculation system using java netbeans/',
      'assets/projects/software/graduation and academic honors calculation system using java netbeans/'
    ]
  },

/* ════ MULTIMEDIA INTERAKTIF ════ */
  {
    num:'28', emoji:'⚡',
    tags:['multimedia','other','Interactive Learning Media'],
    date:'',
    cats:['Multimedia','Interactive Learning Media','Educational Game','Adobe Flash', 'ActionScript', 'Animation'],
    catColors:['syn-cyan','syn-teal','syn-green','syn-yellow','syn-orange','syn-pink'],
    title:'Interactive Learning Media for Uniform Linear Motion (ULM)',
    features:['Meter reading input','Auto bill calculation','Invoice generation','Payment confirmation','Outstanding bill reports'],
    problem:'Many students struggle to understand Uniform Linear Motion because physics concepts are often abstract and lack engaging interactive learning media.',
    solution:'Developed an interactive learning platform that combines learning materials, animations, quizzes, and educational games to make Uniform Linear Motion concepts easier and more engaging to understand.',
    contribution:[
      'Developed 480 frames learning pages and modules using Adobe Flash and ActionScript.',
      'Built 3 main modules: user guide, learning materials, and assessments.',
      'Implemented 5+ interactive animations and visual illustrations to explain Uniform Linear Motion concepts.',
      'Developed 2 assessment features, including an interactive quiz and an educational game.',
      'Designed 20+ visual assets, including illustrations, icons, buttons, and interface elements.',
      'Developed the complete navigation flow and user interactions using ActionScript.'
    ],
    result:'The learning media delivers a more interactive learning experience through animations, illustrations, quizzes, and educational games, making Uniform Linear Motion concepts easier to understand.',
    stack:['Adobe Flash','ActionScript 3.0','SWF','Fla'],
    tools:['Adobe Flash Professional CS6','Canva'],
    github:'',demo:'',portfolio:'',
    slides:['assets/projects/multimedia/interactive learning media for uniform linear motion/GLB.gif']
  },
];

/* stack → color map */
const STACK_COLORS = {
  'Python':'syn-cyan','TensorFlow':'syn-blue','Scikit-learn':'syn-blue','Flask':'syn-orange',
  'React':'syn-yellow','Tailwind CSS':'syn-cyan','Pandas':'syn-green','NumPy':'syn-green',
  'OpenCV':'syn-purple','PyTorch':'syn-orange','Transformers':'syn-purple','HuggingFace':'syn-purple',
  'NLTK':'syn-pink','Librosa':'syn-pink','MFCC':'syn-purple','PHP':'syn-blue',
  'CodeIgniter 4':'syn-red','MySQL':'syn-green','JavaScript':'syn-yellow','HTML/CSS':'syn-yellow',
  'Bootstrap':'syn-blue','R':'syn-blue','ggplot2':'syn-orange','dplyr':'syn-green',
  'MobileNetV2':'syn-purple','CNN':'syn-blue','SVM':'syn-cyan','Random Forest':'syn-green',
  'Arduino/ESP32':'syn-teal','MQTT':'syn-teal','C++':'syn-blue','Plotly':'syn-orange',
  'Matplotlib':'syn-orange','Seaborn':'syn-yellow','WordCloud':'syn-pink','corrplot':'syn-purple',
  'DeepFace':'syn-purple','Node-RED':'syn-orange','Grafana':'syn-cyan','REST API':'syn-orange',
  'Canvas API':'syn-yellow','CSS Variables':'syn-purple','Telegram Bot API':'syn-teal',
  'tidyr':'syn-blue','R Markdown':'syn-orange','DeepLearning':'syn-purple',
};
function stackColor(t){return STACK_COLORS[t]||'syn-blue';}
